name: Build and Inject dylib into IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies & Azule
        run: |
          brew install dpkg ldid
          curl -LO https://raw.githubusercontent.com/Al423/Azule/main/azule
          chmod +x azule
          mkdir -p $HOME/bin
          mv azule $HOME/bin/azule
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Download IPA
        run: |
          curl -L "https://files.catbox.moe/4rf15n.ipa" -o app.ipa

      - name: Setup Theos & SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip -q master.zip
          mv sdks-master/* $HOME/theos/sdks/
          rm -rf master.zip sdks-master

      - name: Build Dylib
        run: |
          make clean package FINALPACKAGE=1 THEOS=$HOME/theos

      - name: Inject Dylib into IPA
        run: |
          DYLIB_PATH=$(find .theos/obj -name "*.dylib" | head -n 1)
          azule -i app.ipa -o output -f "$DYLIB_PATH" -n 8BallPool-Modded

      - name: Upload Modded IPA
        uses: actions/upload-artifact@v4
        with:
          name: 8BallPool-Injected-IPA
          path: output/*.ipa
